### ISSUE TITLE
ValueError: Predictions and gold data have different number of lines.

### ISSUE THREAD

**Issue by drussellmrichie** [felipebravom/EmoInt#2]
So I just dl'ed the repo, moved the pred and gold files into the base directory (might want to add a note for people to do that?), and ran:

`python evaluate.py 1 anger-pred.txt anger-gold.txt`

And I got:

```
Traceback (most recent call last):
  File "evaluate.py", line 162, in <module>
    main(sys.argv[1:])
  File "evaluate.py", line 128, in main
    result=evaluate(pred,gold)
  File "evaluate.py", line 104, in evaluate
    raise ValueError('Predictions and gold data have different number of lines.')
ValueError: Predictions and gold data have different number of lines.
```

I inspected each file, and, indeed, gold has many, many more lines than pred.

Any idea what's up with this?

**Comment by felipebravom** [comment]
Hi,
Which gold file are you using?
Cheers,
Felipe

**Comment by drussellmrichie** [comment]
anger-gold.txt

**Comment by felipebravom** [comment]
Hi
I think you are comparing files from different competitions. The only gold
data that we have published so far is the one of the WASSA 2017
competition.
Make sure you are using the right files.
Cheers.

**Comment by drussellmrichie** [comment]
Yep, that was the issue. I didn't notice that there were multiple golds -- I used the gold from dev_data and now it's working.

Thanks!

**Comment by felipebravom** [comment]
Great.
Cheers.
